// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrgMember struct {
	ID        int32
	MemberID  string
	OrgID     string
	CreatorID string
}

type Organisation struct {
	OrgID       string
	Name        string
	Description pgtype.Text
	UserID      string
}

type User struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Password  string
	Phone     pgtype.Text
}
