// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: org_members.sql

package sqlc

import (
	"context"
)

const createOrgMember = `-- name: CreateOrgMember :one
insert into org_members (member_id, org_id, creator_id)
values ($1, $2, $3)
RETURNING member_id, org_id, creator_id
`

type CreateOrgMemberParams struct {
	MemberID  string
	OrgID     string
	CreatorID string
}

func (q *Queries) CreateOrgMember(ctx context.Context, arg CreateOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, createOrgMember, arg.MemberID, arg.OrgID, arg.CreatorID)
	var i OrgMember
	err := row.Scan(&i.MemberID, &i.OrgID, &i.CreatorID)
	return i, err
}
